### ISSUE TITLE
Addon keeps rebooting (due to failing Docker healthchecks?)

### ISSUE THREAD

**Issue by nathanielks** [jkunczik/home-assistant-omada#10]
Hi hi!

Thank you so much for putting this together, it makes my life so much easier!

One thing I'm encountering is the add-on keeps rebooting every 5 minutes or so. The web console works fine, but it will still crash regardless. I realized this is likely due to the Docker healthchecker failing. I don't have any details on how to fix this yet, but I wanted to open this up and I'll log my notes as I find things out!

For context, running this in Home Assistant 2023.8.1, OS 10.4 on a Raspberry Pi 4 Model B 2G.

**Comment by nathanielks** [comment]
Confirmed, it had to do with the healthchecks. `/healthcheck.sh` isn't executable in the image, so it fails with `/bin/sh: 1: /healthcheck.sh: Permission Denied`. Home Assistant is caching my fork of the repo and I'm not quite sure how to bust the cache yet, but I'll report back when I have a fix 👍

**Comment by DraTrav** [comment]
Thank you for this fix! you arnt the only to have this issue, though I coudnt repeat on the mutliple systems I tried it on, thank you so much!
