### ISSUE TITLE
Switching to Stable from Beta

### ISSUE THREAD

**Issue by brooksben11** [jkunczik/home-assistant-omada#23]
Not an issue, but more just a question. What's the best way to switch to Stable from the Beta? I originally setup the Beta because I'm using an x86 but it appears the Stable now supports it as well. Would I just need to do a backup (or whatever's it's called WITHIN Omada, not an add-on backup) and then restore from that after setting up the Stable add-on?

**Comment by brooksben11** [comment]
Found the closed issue for going from stable to beta.

**Comment by jkunczik** [comment]
For others looking for this answer, see issue #17

**Comment by brooksben11** [comment]
FYI - Just tried it, and unfortunately that method doesn't work for me at the moment. The Omada restore process requires that you restore from a version equal to or less than the current, and my current beta version is higher than the current stable. I've made myself a reminder to try again once the stable version has been updated to a higher version than my current beta version.

Not a big deal, just figured I'd make a note to save other folks the time (and any confusion).
