### ISSUE TITLE
How to install this Addon in Home Assistant?

### ISSUE THREAD

**Issue by dinomyte76** [jkunczik/home-assistant-omada#3]
Hi @jkunczik, hi @DraTrav,

is there any chance you tell me how i can install your addon in HA? I would love to use it...

Thanks and cheers from Cologne Germany ;-)
Dino

**Comment by DraTrav** [comment]
Hi, if you aren't familiar with installing third-party repositories it's pretty easy!
1. go to home assistant -> settings -> addons -> addon store
2. Click the hamburger menu (The three dots in the top right corner)
3. Click repositories
4.  at the bottom there should be a space to paste the GitHub link: https://github.com/jkunczik/home-assistant-omada
5. You might have to refresh the page but it should show up in the store after that under "Home Assistant Omada"

It'll take a couple of minutes to install.

Hopefully, this helps!

**Comment by dinomyte76** [comment]
Hi @DraTrav,

this helped a lot, it works! I was indeed not familiar yet on that part yet.

Thanks a lot for your support!!

**Comment by FabianoRegra** [comment]
> Hi, if you aren't familiar with installing third-party repositories it's pretty easy!
> 
> 1. go to home assistant -> settings -> addons -> addon store
> 2. Click the hamburger menu (The three dots in the top right corner)
> 3. Click repositories
> 4. at the bottom there should be a space to paste the GitHub link: https://github.com/jkunczik/home-assistant-omada
> 5. You might have to refresh the page but it should show up in the store after that under "Home Assistant Omada"
> 
> It'll take a couple of minutes to install.
> 
> Hopefully, this helps!


Hey guys,

I'm trying to install it but I'm getting the following error:

Can't install jeruntu/home-assistant-omada-stable:5.15.8.2: 401 Client Error for http+docker://localhost/v1.47/auth: Unauthorized ("Get "https://registry-1.docker.io/v2/": unauthorized: incorrect username or password")
