### ISSUE TITLE
Configure Home Assistent integration 

### ISSUE THREAD

**Issue by carstenschroeder** [jkunczik/home-assistant-omada#30]
Hi!

I would like to add the Home Assistent integration and connect it to the addon. What host name do I need to use in the config flow?

**Comment by Jeruntu** [comment]
Hello,

The host name is the same as Home Assistant itself, it only uses a different port. By default the port is 8043. I haven't used the integration, so I'm not sure if this is what you mean.

**Comment by carstenschroeder** [comment]
Ok, thanks I missed to add the port. It works with host: homeassistant.local:8043
