### ISSUE TITLE
v5.14.26.1 available in MBentley repo

### ISSUE THREAD

**Issue by chiefcomm** [jkunczik/home-assistant-omada#31]
@DraTrav @jkunczik any possibility to update to v5.14.26.1 which is now available in MBentley repo.  I was hoping I could help out on this but it was far above my skillsets :-(

**Comment by DraTrav** [comment]
I should be able to get this done later today or Saturday. I'm a little busy but I'll try to have it done by Monday!

**Comment by DraTrav** [comment]
I am finished and updated to the latest!

**Comment by chiefcomm** [comment]
Thank you legend
