### ISSUE TITLE
Unable to launch my site on the Local Interface

### ISSUE THREAD

**Issue by satvikknischal** [jkunczik/home-assistant-omada#37]
I am extremely new to HA and Networking as well, I found this alternative for the Omada Physical Controller and basically jumped at it, and am very grateful for all the work everyone has put into it. 
The issue is that as soon as I click on launch site, I am sent back to the login page and then when I enter my credentials it never logs me in and keeps dropping me back to the login page again in an infinite loop. 

Edit: NVM just had to disable an adblocker that I had enabled on my browser to get it running. Its working perfectly now.

**Comment by MisterTechnik** [comment]
Thank you, that saved me a lot of troubleshooting. In my case it was my dark mode plugin or maybe both or the ad blocker change didn't apply after the first refresh. Either way it's fixed now.
