### ISSUE TITLE
CPU Load increased up to 80%

### ISSUE THREAD

**Issue by fetze82** [jkunczik/home-assistant-omada#4]
Hey,
I installed the Omada Controller in HA and i worked well.
But, bevor i Installed the Omada Controller, the Raspi 4 4GB hat a CPU Load with approx. 2-4%
Now, with running Omada Controller the CPU load is approx. 80%
I guess it isn`t normal the load increase that much?
Greatings Chris
![Omada](https://user-images.githubusercontent.com/39420574/219349057-5e965a93-1b00-4466-919a-576a62786b31.jpg)

**Comment by jkunczik** [comment]
This is indeed strange. My addon runs at 0,3% processor load. When running the add-on for the first time, the CPU load can be quite high, because the controller performs the initial setup, but not over that many hours.

**Comment by DraTrav** [comment]
If you restart the addon does the same behavior happen? 
for the first 5 mins after starting the addon, it is expected to run pretty high as the setup is quite intense for something like the raspberry pi.
do you mind if I ask a few questions about your network? 
How many access points are you using? How many devices are connected to them?

Would you also mind supplying a log from home assistant
this can be accessed from 
Settings > Logs, then in the top right you can select the addon installed and download the appropriate log
