### ISSUE TITLE
Installing the latest beta wiped all settings

### ISSUE THREAD

**Issue by mclever** [jkunczik/home-assistant-omada#42]
Reverting to backup of add-on

**Comment by DraTrav** [comment]
We are aware and are currently looking into it. We made some pretty big changes. The best solution right now is too
1. load the home assistant backup
2. Open Omada and backup configuration
3. update
4.load configuration after the first setup page

**Comment by DraTrav** [comment]
> Thanks @DraTrav !
> 
> I fear the persistence thing stems from the fact that I changed the symlinks. I had hoped that because their relative path in `/data` was the same as before there shouldn't be any issue. Maybe it has something to do with the way I am checking if `/data/data`is empty
> 
> https://github.com/jkunczik/home-assistant-omada/blob/b93b6018414b0b3757488eb4ce13376b00bbf103/Omada%20Beta/entrypoint.sh#L11

Moving the conversation to the related issue thread.

The relative path looks fine to me as well. I'm also a little lost on how you're checking what could be causing that, I'm honestly fine if we want to just put a warning at the top of the change log to backup the Omada configuration and restore it after.

**Comment by mclever** [comment]
I don't know how to grab that info for you, but happy to if you can walk me through how to gather

**Comment by mclever** [comment]
Restored backup to latest stable and all is well. Thanks
