### ISSUE TITLE
Use HA SSL - Not working

### ISSUE THREAD

**Issue by rpruden** [jkunczik/home-assistant-omada#46]
After the latest upgrade, if you have the option enabled to use the home Assistant SSL certificate it fails to start the addon. If you disable this feature, it will start fine. I am using a wildcard LetEncrypt cert from the built in plugin.

`[12:49:19] INFO: Create 'logs' directory inside persistent /data volume, if it doesn't exist.
[12:49:20] INFO: Use SSL from Home Assistant
/entrypoint.sh: line 20: SSL_CERT: unbound variable`

**Comment by Jeruntu** [comment]
It likely broke after the major refactor. I just merged a fix, should be working now.

**Comment by jkunczik** [comment]
Thanks for the info. I look into it.

**Comment by Jeruntu** [comment]
It is fixed, but a new version docker image has to be pushed. Will be done with #50
