### ISSUE TITLE
Typo in latest changelog?

### ISSUE THREAD

**Issue by h3llrais3r** [jkunczik/home-assistant-omada#49]
Latest changelog mentions version: `5.15.14.32.2 - 2024-09-5`
Shouldn't it be: `5.14.32.2 - 2024-09-5`
![image](https://github.com/user-attachments/assets/04dd245e-d5c3-4861-a336-165b995d4d30)

**Comment by jkunczik** [comment]
Thanks! Your absolutely right!

**Comment by Jeruntu** [comment]
I fixed it in this PR #50
