### ISSUE TITLE
Publish image to Docker Hub

### ISSUE THREAD

**Issue by mancontr** [jkunczik/home-assistant-omada#5]
Right now, this addon builds the Docker image on the Home Assistant machine during install.
This works fine, but makes the install process very slow (especially on small devices such as a Pi), and makes backups bigger and impractical.
Would you consider publishing the images on Docker Hub, and referencing them from the addon, instead of building them locally?
Is there anything preventing this? I'm willing to help if needed.
Thanks for your awesome work!

**Comment by jkunczik** [comment]
That's a great idea! The only thing that stopped me was my limited time. I would really appreciate it if you would be willing to contribute this!

**Comment by mancontr** [comment]
Awesome, thanks! After a quick check, it seems all needed for this would be:
1. Push the images to Docker Hub
2. Update the `config.json` adding a line pointing to the Docker repository

For the first step, I think it should be pushed to your own Docker account, so you can keep control of it, and users can trust the image. These would be the steps to publish each version; feel free to edit the names as needed:
 ```sh
cd "Omada Stable"
docker buildx build --platform linux/arm64 -t jkunczik/home-assistant-omada-stable:5.0.30 --push .
cd ..

cd "Omada Beta"
docker buildx build --platform linux/arm64,linux/amd64 -t jkunczik/home-assistant-omada-beta:5.9.1 --push .
cd ..
```
Note that on the first build command, I added a version number to the stable version (instead of "stable") so it can be updated in the future if needed.
For the beta build to work, we can't have two Dockerfiles, as this doesn't work with buildx (AFAIK). I've sent a PR (#7) merging them into one, after which the command above works correctly.

After publishing the images, all that remains is adding the following to each `config.json`:

At the Stable repository:
```json
    "image": "jkunczik/home-assistant-omada-stable",
    "version": "5.0.30",
```
(We need to update the version so it matches the command above)

At the Beta repository:
```json
    "image": "jkunczik/home-assistant-omada-beta",
```

I could send another PR with the config changes, but I think it's better to wait until we know the final image name, in case you change it (or have a different username on Docker).

... and that's it! :partying_face:

**Comment by mancontr** [comment]
Note that you could publish both stable and beta at the same repository on Docker, just tagging them as different versions, instead of having two repositories.
It's up to you how you'd like to organise it.

If you decide to go this way, the steps are still the same: just use the same repo name for both versions, keeping the different version numbers.

**Comment by jkunczik** [comment]
Thank you so much for the guide! I will get to it ASAP.

**Comment by mancontr** [comment]
You're welcome! And thanks for all your hard work.

I tried the steps myself (short of publishing the images, of course), and everything worked perfectly, but please let me know if you run into any problem. Thanks!

**Comment by DraTrav** [comment]
I considered this in pull #8, I decided it was probably best for @jkunczik to host the docker image on his docker so I reverted those changes, however ill gladly host them if he'd rather.

**Comment by Jeruntu** [comment]
I also think this is a good idea. @jkunczik are you willing to host this yourself or should someone else do it?

**Comment by jkunczik** [comment]
Hey all. I am quite busy at the moment. @DraTrav If you are willing to host the images, this would be great! I don't think I currently have the time to maintain them properly.

**Comment by Jeruntu** [comment]
@DraTrav would you like to that? I also wouldn't mind setting it up.

**Comment by DraTrav** [comment]
I can set it up this week. And I’ll close it once I push the changes.

**Comment by DraTrav** [comment]
Images are now hosted and should be up to date! I'll keep up with uploading them to docker as I update this repository.
