### ISSUE TITLE
Addon removed notification

### ISSUE THREAD

**Issue by h3llrais3r** [jkunczik/home-assistant-omada#58]
Hi, since last week (probably since new version?) I'm getting the following warning in HA.

![image](https://github.com/user-attachments/assets/9f28d094-e8c6-40c2-b2f7-a84f686937ff)

Any suggestion on how to migrate without losing my existing data/config?

**Comment by Jeruntu** [comment]
The beta has not been removed from the repository. Are you sure the repository is still in your add-on store?

If that's not the issue you can export your configuration with your current installation, and import it again in a new fresh installation. 

Hope this helps.

**Comment by h3llrais3r** [comment]
I don't understand it either...
Repo is still there, but I have no clue why it complains about the removal...
![image](https://github.com/user-attachments/assets/a36f90c9-78dc-4a63-84bd-5e57cd817140)

**Comment by h3llrais3r** [comment]
> If that's not the issue you can export your configuration with your current installation, and import it again in a new fresh installation.

Settings backup is sufficient? 
![image](https://github.com/user-attachments/assets/c45f701e-39bd-43de-9c11-3f377051372a)

**Comment by h3llrais3r** [comment]
Correct, it seems that the identifier was changed (_beta, _dev or _stable being added now).

**Comment by BlackHoleFox** [comment]
Looks like it changed in https://github.com/jkunczik/home-assistant-omada/commit/515633461bd639cb689ad15b57138a5fb255c8c0#diff-c4dd624a9516bb9b3c3e9ebb63af471760163e07ea4fced24ec7b5f02f88c352R5

**Comment by h3llrais3r** [comment]
So only way is installing the new one and migrating the config?

**Comment by Jeruntu** [comment]
That's the only way at the moment. I changed it to make the distinction more clear, didn't know it'll cause this issue. Sorry about that.

**Comment by h3llrais3r** [comment]
Just migrated my config to the new stable addon. (Since I forgot to backup the clients, I had to manually rename all my devices, as the custom names seem not to be included in the backup)

**Comment by h3llrais3r** [comment]
Maybe add a note somewhere in the changelog or readme to indicate for people who might face the same? 😉

**Comment by Jeruntu** [comment]
That's a good point. I included a warning in the changelog.
