### ISSUE TITLE
Is there a plan to port this tool to other platforms?

### ISSUE THREAD

**Issue by RalfPfitzner** [jkunczik/home-assistant-omada#6]
Hi, I'm running HAOS on x86-64, not on a Raspberry.

So unfortunately it's not possible to install this add-on.

Do you plan to port it to this platform?

Thanks
Ralf

**Comment by contactnat** [comment]
I second this request

**Comment by jkunczik** [comment]
I added support for amd64 in the Beta channel. Could you test if it is working, since I currently don't have a X86-64 system running home assistant?

**Comment by contactnat** [comment]
> I added support for amd64 in the Beta channel. Could you test if it is working, since I currently don't have a X86-64 system running home assistant?

So far so good, starts up fine and can navigate to start page - I will try restoring a backup of my prod instance next and report back soon.

**Comment by contactnat** [comment]
yup works well, my prod instance is working on docker on a proxmox vm, my home assistant is installed on the same proxmox under its own vm.

**Comment by RalfPfitzner** [comment]
Working as expected!
Thanks

**Comment by jkunczik** [comment]
Thanks for testing!

**Comment by bezigebever** [comment]
Is this now integrated in the stable release ?

**Comment by jkunczik** [comment]
With the latest update it is!

**Comment by bezigebever** [comment]
@jkunczik so I can safely upgrade to the stable release now ?
I assume I need the backup / restore procedure for this ?

**Comment by jkunczik** [comment]
Theoretically, yes. There is an issue that you can't restore the configuration from a later version into an earlier version (see #23)

**Comment by bezigebever** [comment]
@jkunczik  I'm running Beta 5.11.0 which runs Omada 5.13.10
On what Omada version are we for the stable branch ?

**Comment by jkunczik** [comment]
I just merged a PR, which also updates Stable to Omada 5.13.10.

You can run the Omada update (at least nothing bad should happen), but once you restart the addon, all changes will be lost.

**Comment by bezigebever** [comment]
@jkunczik successfully migrated from beta to stable. Many thanks !
