### ISSUE TITLE
New Stable Version Available - 5.15.6.7

### ISSUE THREAD

**Issue by chiefcomm** [jkunczik/home-assistant-omada#70]
I notice the latest Stable in Omada is now 5.15.6.7.

What is the timeline that jkunczik/home-assistant-omada will have 5.15.6.7 set as the Stable version? I had 5.15.6.7 running in my Dev but rolled back to 5.14.32.4 as I did not anticipate 5.15.6.7 being released as the stable version.

I would create a PR but this was a little beyond my skillset.

![image](https://github.com/user-attachments/assets/7d0ff515-2807-44db-9224-bf8c556597a4)

**Comment by Jeruntu** [comment]
I didn't realise this version was already stable. Thank you for letting us know, I just upgraded Stable to the latest 5.15.6.7 version.

**Comment by chiefcomm** [comment]
Perfect thanks
