### ISSUE TITLE
Update Omada version

### ISSUE THREAD

**Issue by mclever** [jkunczik/home-assistant-omada#9]
Thank you for this add-on. I'm testing out the beta release on a micro PC. 

What should we be doing to keep the Omada version up to date? Trying to port from a container to HA addon and the versions are different. Beta release of the add-on isn't on the latest and greatest Omada

**Comment by mclever** [comment]
@DraTrav @jkunczik any recommendations? The beta container keeps rebooting on me and hoping an update makes it stable on HA

**Comment by DraTrav** [comment]
Hi!, I just merged to the latest, you should receive the update soon. please report back to me if it still is rebooting for you!

**Comment by DraTrav** [comment]
You can also force the repo to recheck for an update by going to the addon page and clicking the "check for update" button in the top right corner

**Comment by mclever** [comment]
Thanks, running now and will report back in an hour if it reboots.

If it does, what's the best way to capture logs?

________________________________

**Comment by DraTrav** [comment]
The best way would be under settings > system > logs 
then click in the top left corner and you should be able to click on "Omada controller beta"

**Comment by mclever** [comment]
It rebooted already. Not sure if this bin file can be uploaded

________________________________

**Comment by DraTrav** [comment]
it shoudnt be a .bin file, it should be a .log file. 
at the location you can see the log there should be a download button

<img width="1038" alt="image" src="https://github.com/jkunczik/home-assistant-omada/assets/42803478/0d6bca92-061f-4382-962d-613d58cce0dd">

**Comment by mclever** [comment]
INFO: Validating user/group (omada:omada) exists with correct UID/GID (508:508)
INFO: Group (omada) exists; skipping creation
INFO: User (omada) exists; skipping creation
INFO: Time zone set to 'America/Los_Angeles'
INFO: Starting Omada Controller as user omada
tail: cannot open '/opt/tplink/EAPController/logs/server.log' for reading: No such file or directory
tail: '/opt/tplink/EAPController/logs/server.log' has appeared; following new file
06-19-2023 19:06:32.958 INFO [main] [] c.t.s.o.s.OmadaLinuxMain(): record: start the omada controller
06-19-2023 19:06:32.962 INFO [main] [] c.t.s.o.s.OmadaLinuxMain(): record: set property finished
06-19-2023 19:06:32.965 INFO [main] [] c.t.s.o.s.OmadaLinuxMain(): record: configure log finished
06-19-2023 19:06:32.967 INFO [main] [] c.t.s.o.s.OmadaBootstrap(): record: bootstrap prepare
06-19-2023 19:06:32.969 INFO [log4j-thread] [] c.t.s.o.c.o.a.b(): success to load configuration omada.properties
06-19-2023 19:06:32.970 INFO [log4j-thread] [] c.t.s.o.c.o.OmadacType(): omadacType: Local Controller
06-19-2023 19:06:32.986 INFO [main] [] c.t.s.o.s.OmadaBootstrap(): going to start local mongod.
06-19-2023 19:06:35.000 INFO [main] [] c.t.s.o.s.s.b(): mongodb process id is 56
06-19-2023 19:06:35.003 ERROR [main] [] c.t.s.f.c.FacadeUtils(): facadeMsgEnable is not enable, msg: Mongo DB server started
06-19-2023 19:06:35.004 INFO [main] [] c.t.s.o.s.s.b(): Mongo DB server started
  . ____ _ __ _ _
 /\\ / ___'_ __ _ _(_)_ __ __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/ ___)| |_)| | | | | || (_| | ) ) ) )
  ' |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot :: (v2.6.6)
06-19-2023 19:06:35.349 INFO [main] [] c.t.s.o.s.OmadaBootstrap(): record: bootstrap record finished
06-19-2023 19:06:35.349 INFO [main] [] c.t.s.o.s.OmadaBootstrap(): record: bootstrap startup
06-19-2023 19:06:35.394 INFO [main] [] c.t.s.o.s.OmadaBootstrap(): record: start run omada tasks
06-19-2023 19:06:35.394 INFO [main] [] c.t.s.o.s.t.SpringBootStartUpTask(): record: task SpringBootStartupTask start
06-19-2023 19:06:35.863 INFO [main] [] c.t.s.o.s.OmadaLinuxMain(): Starting OmadaLinuxMain v5.9.31 using Java 17.0.7 on 7e9b5ada-omada-controller with PID 7 (/opt/tplink/EAPController/lib/local-starter-5.9.31.jar started by omada in /opt/tplink/EAPController/lib)
06-19-2023 19:06:35.865 INFO [main] [] c.t.s.o.s.OmadaLinuxMain(): No active profile set, falling back to 1 default profile: "default"
06-19-2023 19:06:41.680 WARN [main] [] o.s.d.c.CustomConversions(): Registering converter from class java.time.LocalDateTime to class org.joda.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
06-19-2023 19:06:43.010 WARN [main] [] o.s.d.c.CustomConversions(): Registering converter from class java.time.LocalDateTime to class org.joda.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
06-19-2023 19:06:46.687 INFO [main] [] c.t.s.l.c.s.d.CacheLogConsumeHandler(): log mq consume task is start...
06-19-2023 19:06:46.689 INFO [main] [] c.t.s.o.s.OmadaLinuxMain(): Started OmadaLinuxMain in 11.212 seconds (JVM running for 14.415)
06-19-2023 19:06:46.768 INFO [main] [] c.t.s.o.c.p.s.e(): Handling event: ***@***.***
06-19-2023 19:06:46.778 INFO [main] [] c.t.s.o.m.d.p.b.a(): manager maintenance Handling event: ***@***.***
06-19-2023 19:06:46.796 INFO [main] [] c.t.s.o.l.p.c.c.b.b(): Handling event: ***@***.***
06-19-2023 19:06:46.835 INFO [main] [] c.t.s.o.s.t.SpringBootStartUpTask(): record: task SpringBootStartupTask finished
06-19-2023 19:06:46.835 INFO [main] [] c.t.s.o.s.t.OmadacInitTask(): record: before OmadacInitTask
06-19-2023 19:06:46.851 INFO [main] [] c.t.s.o.s.t.OmadacInitTask(): record: before init bean
06-19-2023 19:06:47.557 INFO [main] [] c.t.s.e.s.c.c(): start schedule remove expire device... period = 10
06-19-2023 19:06:47.564 INFO [main] [] c.t.s.e.s.c.c(): update rateLimiterCache, permitsPerSecond = 5.0
06-19-2023 19:06:47.705 INFO [main] [] c.t.s.o.m.d.p.t.TransportConfiguration(): manager workGroup core thread num is 16, max thread num is 16
06-19-2023 19:06:47.760 INFO [main] [] c.t.s.o.m.d.d.m.m.c.DeviceMsgConfig(): setMsgThreadPool thread coreSize is 6, maxSize is 6,queue size is 4500
06-19-2023 19:06:49.028 INFO [main] [] c.t.s.o.m.d.p.t.TransportConfiguration(): upgradeSendReq workGroup core thread num is 1, max thread num is 1
06-19-2023 19:06:49.675 INFO [main] [] c.t.s.o.m.c.d.m.s.w.s.c.WirelessGroupConfig(): ssidWorkerGroup thread size is 6, queue size is 1500
06-19-2023 19:06:50.949 INFO [main] [] c.t.s.o.s.t.OmadacInitTask(): record: after init bean
06-19-2023 19:06:51.020 INFO [main] [] c.t.s.o.s.d.a(): Db unchanged. No need to compatible or init data.
06-19-2023 19:06:51.053 INFO [main] [] c.t.s.o.s.t.OmadacInitTask(): succeed get default omadac OmadacVO(id=705dc54f31d217fcfb8e9eec82ff7f1d, name=HA Add-on)
06-19-2023 19:06:51.083 INFO [main] [] c.t.s.o.s.t.OmadacInitTask(): record: before init for hwc
06-19-2023 19:06:51.083 INFO [main] [] c.t.s.o.s.t.OmadacInitTask(): record: after init for hwc
06-19-2023 19:06:51.108 INFO [main] [] c.t.s.o.d.g.c.d.ThreadConfiguration(): device-gateway datatrack workGroup core thread num is 12, max thread num is 12
06-19-2023 19:06:51.221 INFO [main] [] c.t.s.o.c.p.c.o.s.ActiveSiteCacheImpl(): Scheduled ActiveSitesCache period flush buf task at fixed rate of 30000 millis.
06-19-2023 19:06:51.809 INFO [main] [] c.t.s.o.d.g.c.f.b.c(): file download mq consume task is start...
06-19-2023 19:06:51.833 INFO [main] [] c.t.s.o.m.d.p.t.TransportConfiguration(): adopt workGroup core thread num is 8, max thread num is8
06-19-2023 19:06:51.975 INFO [main] [] c.t.s.o.m.d.p.t.TransportConfiguration(): discovery workGroup core thread num is 2, max thread num is 10
06-19-2023 19:06:52.013 INFO [main] [] c.t.s.o.m.l.p.e.LicenseEventCenterProperties(): licenseManagerTopic: omada.cloud.license.prd.topics
06-19-2023 19:06:52.139 INFO [main] [] c.t.s.o.p.p.r.a.c(): init nioEventLoopGroup

________________________________

**Comment by DraTrav** [comment]
May I ask the specs of your system? also how do you know it is restarting?

**Comment by mclever** [comment]
Seeing the uptime in the interface. It has only done it once since the update at least. I'll see what I can see tomorrow.

It's a 5 year old micro PC, not sure on proc model, looks like 6 core, 16gb ram from what I can see on mobile HA and barely using any of the resources.

________________________________

**Comment by DraTrav** [comment]
You should see if you can access the web interface, make sure you connect threw the local HASS connection. I'll do some more testing tonight to see if maybe it's the amd64 support not working correctly.

**Comment by mclever** [comment]
Uptime when I just checked was 3 minutes so it's still rebooting frequently.

Logs seem to roll on boot. Any way to get the crash info?

**Comment by DraTrav** [comment]
The full log would show this. I'm not quite sure why its rebooting, I'm failing to replicate this on my systems though I'll continue to investigate it

**Comment by mclever** [comment]
Not sure what you mean by full log. The addon log recycles when the container is rebooted. Haven't seen uptime of more than 10 mins when checking the web interface a few times today.

Also, HTTP Port for Controller Management
8088 was same as the http portal. Can't login via http if they are the same.

**Comment by DraTrav** [comment]
Can you explain in more detail what you mean by "HTTP Port for Controller Management
8088 was same as the http portal. Can't log in via http if they are the same."

The ports can not change they are set by Tp-link. They are not configurable. the configuration just shows what ports the docker container exposes and should not be changed.

if you have a port conflict that might be what's causing the rebooting.

do you mean the uptime inside the Omada controller container itself?

**Comment by mclever** [comment]
HTTP Port for Portal was 8088 and I changed to 8888 via the web ui

Only reason I tried that was I couldn't login when I was trying to use http instead of https

________________________________

**Comment by mclever** [comment]
Uptime from here


________________________________

**Comment by DraTrav** [comment]
the container should be accessed via https://homeassistant.local:8043

did you mean to attach an image?

**Comment by mclever** [comment]
![Screenshot_20230620-195813](https://github.com/jkunczik/home-assistant-omada/assets/60011614/e0da6135-a270-4f73-bee3-cba7142257a9)
![Screenshot_20230620-200152](https://github.com/jkunczik/home-assistant-omada/assets/60011614/6fd3a323-1473-437a-9213-4b4172b09fe9)

Ah, apparently sending in email doesn't work. Here they are

Http 8088 works just fine for accessing the ui

**Comment by DraTrav** [comment]
are there any errors inside the controller? you should be able to them from the sidebar.
<img width="171" alt="image" src="https://github.com/jkunczik/home-assistant-omada/assets/42803478/007ef039-a471-49ca-9204-b4a55a07bffa">

**Comment by mclever** [comment]
Just my failed login attempts from fat fingering password

**Comment by DraTrav** [comment]
I'm sorry this is taking so long, troubleshooting home assistant addons is a pain since logs aren't stored in an easily accessible way.

Do you have watchdog enabled for this addon?

**Comment by mclever** [comment]
All good, I appreciate you.

Yes watchdog is enabled

________________________________

**Comment by DraTrav** [comment]
Alright, first let's try disabling the watchdog. if the docker image itself is crashing then it should leave a crash message in the home assistant add-on log.

**Comment by mclever** [comment]
Well with watchdog disabled I made it past 10 minutes and still counting

**Comment by mclever** [comment]
17 minutes and still counting...

**Comment by DraTrav** [comment]
How strange? The home assistant watchdog service must have kept flagging it as "crashed". which would explain why your logs don't show any error. I'll try to figure out why. for now, keep it disabled.

**Comment by mclever** [comment]
Yeah sounds like a plan. Have watchdog enabled on all my other add-ons.

Going to see if an addon stopping can be used as a trigger for an automation.

**Comment by mclever** [comment]
FYI there is a sensor which can tell you if an addon is running, but you have to enable it in settings > devices > omada > expand sensors > running > gear > enable

**Comment by DraTrav** [comment]
Thank you for the heads-up about the sensor! I'm glad we got it figured out for you.

**Comment by mclever** [comment]
No more reboots overnight since disabling watchdog

**Comment by mclever** [comment]
Has been running fine all night with watchdog enabled so I moved my devices over and enabled watchdog again. Fingers crossed!!!

**Comment by DraTrav** [comment]
Thanks for Keeping me updated, if it work I'll close the issue. Might have been just some weird issue with Home assistant.

**Comment by mclever** [comment]
Yeah seems to be working. So maybe without devices the usage is so low HA thinks it's dead?

Anywho, thanks for your time!
